project_id = "dppyamtmjzmmkzjlmiew"

[api]
enabled = true

[functions.sync-discord-roles]
verify_jwt = true

[functions.create-donation-ticket]
verify_jwt = true

[functions.discord-interactions]
verify_jwt = false

[functions.whitelist-moderate]
verify_jwt = true
